import {describe,it,expect} from 'vitest';
import {buildEnquiryDraft} from '../src/lib/contact/enquiry';
const fields={name:'Synthetic visitor',business:'Synthetic business',email:'visitor@example.test',need:'A clearer website',website:'',timing:'',budget:''};
describe('general enquiry draft',()=>{
 it('keeps timing/budget/site optional and prepares only a reviewable email',()=>{const result=buildEnquiryDraft(fields,'hello@wearvalleydigital.com');expect(result.subject).toBe('General project enquiry');expect(result.body).toContain('A clearer website');expect(result.body).not.toContain('Budget context:');expect(result.mailto).toMatch(/^mailto:hello@wearvalleydigital.com\?/);});
 it('encodes user text into the body without adding email headers or rejecting uncertain budgets',()=>{const result=buildEnquiryDraft({...fields,business:'Synthetic\nBcc: foreign@example.test',budget:'Not sure yet',need:'A&B? Need #1'},'hello@wearvalleydigital.com');const url=new URL(result.mailto!);expect([...url.searchParams.keys()]).toEqual(['subject','body']);expect(url.searchParams.get('subject')).toBe('General project enquiry');expect(url.searchParams.get('body')).toContain('Not sure yet');expect(url.searchParams.get('body')).toContain('A&B? Need #1');});
 it('preserves a long Unicode enquiry for manual copying instead of truncating the mail URL',()=>{const need='界'.repeat(1500),result=buildEnquiryDraft({...fields,need},'hello@wearvalleydigital.com');expect(result.mailto).toBeNull();expect(result.body).toContain(need);});
 it('requires core fields and refuses executable or credential-bearing website links',()=>{for(const input of [{...fields,name:''},{...fields,website:'javascript:alert(1)'},{...fields,website:'https://user:password@example.test/'},{...fields,email:'a@example.test\nBcc: b@example.test'}])expect(()=>buildEnquiryDraft(input,'hello@wearvalleydigital.com')).toThrow();expect(()=>buildEnquiryDraft(fields,'hello?bcc=foreign@example.test')).toThrow();});
});
