import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {chromium} from '@playwright/test';
import {createApplication} from '../app.mjs';
import {FirestoreBookingReservations,createReservedIntroCallBooking,createIntroCallBookingReconciler,createReservedIntroCallCancellation} from '../booking-reservations.mjs';
import {createGoogleBookingEventWriter} from '../google-booking-event.mjs';
import {createGoogleBookingCancellation} from '../google-booking-cancellation.mjs';
test('mobile booking: pending reload recovers one durable booking and competing customer sees unavailable',async t=>{
 if(!/^127\.0\.0\.1:\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST??''))throw Error('ISOLATED_EMULATOR_REQUIRED');
 const app=initializeApp({projectId:'demo-wvd-portal'},'booking-ui-'+randomUUID()),db=getFirestore(app);
 t.after(async()=>{await db.terminate();await deleteApp(app);});
 const productId='booking-ui-'+randomUUID(),calendarId=randomUUID()+'@example.test',store=new FirestoreBookingReservations({db,productId,calendarId});
 let inserts=0,cancelOutage=true;const records=new Map();
 const calendar={events:{get:async({eventId})=>{const value=records.get(eventId);if(!value)throw {response:{status:404}};return {data:structuredClone(value)};},insert:async({requestBody})=>{inserts++;const value={...structuredClone(requestBody),status:'confirmed',etag:'"synthetic-version"',conferenceData:{createRequest:{status:{statusCode:'pending'}}}};records.set(value.id,value);return {data:structuredClone(value)};},delete:async({eventId},options)=>{assert.equal(options.headers['If-Match'],'"synthetic-version"');if(cancelOutage)throw Error('synthetic deletion outage');records.delete(eventId);}}};
 const writeEvent=createGoogleBookingEventWriter({calendar,calendarId,productId,requestTimeoutMs:1000});
 const screen=async({starts})=>({slots:starts.slice(0,1).map(start=>({start,end:new Date(Date.parse(start)+1800000).toISOString(),timeZone:'Europe/London'})),provisional:true});
 const book=createReservedIntroCallBooking({store,screen,writeEvent,productId});
 const reconcile=createIntroCallBookingReconciler({store,calendar,calendarId,productId,requestTimeoutMs:1000});
 const cancel=createReservedIntroCallCancellation({store,productId,clock:()=> '2026-10-04T12:00:00.000Z',cancelEvent:createGoogleBookingCancellation({calendar,calendarId,productId,requestTimeoutMs:1000})});
 const origin='http://127.0.0.1:4707';
 const server=createApplication({portal:{},auth:{resolveSession:async()=>null},allowedOrigin:origin,firebaseEmulator:{projectId:'demo-wvd-portal',productId,databaseId:'(default)',mode:'emulator'},callAvailability:{screen,holidayEvidence:{bankHolidayRegion:'england-and-wales',coveredFrom:'2026-01-01',coveredThrough:'2027-12-31',bankHolidays:[],sourceRef:'synthetic'},maxConcurrentRequests:2},callBooking:{productId,calendarId,book,reconcile,cancel,admit:async()=>true,maxConcurrentRequests:2}});
 await new Promise(resolve=>server.listen(4707,'127.0.0.1',resolve));t.after(()=>{server.closeAllConnections();return new Promise(resolve=>server.close(resolve));});
 const browser=await chromium.launch();t.after(()=>browser.close());
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 const evidence=process.env.WVD_TEST_EVIDENCE_DIR;if(evidence)mkdirSync(evidence,{recursive:true});
 const capture=async name=>{if(evidence)await page.screenshot({path:join(evidence,name+'.png'),fullPage:true,scale:'css',animations:'disabled'});};
 await page.goto(origin+'/book');await page.getByLabel('Choose a date').fill('2026-10-06');await page.getByRole('button',{name:'Find available times'}).click();await page.getByRole('button',{name:'09:00',exact:true}).click();await capture('booking-mobile-selected');
 await page.getByRole('button',{name:'Confirm this time'}).click();await page.getByRole('button',{name:'Check booking status'}).waitFor();assert.equal(inserts,1);assert.equal(await page.getByLabel('Choose a date').isDisabled(),true);await capture('booking-mobile-pending');
 const capability=await page.evaluate(()=>sessionStorage.getItem('wvd-development-booking-retry-v1'));await page.reload();await page.getByRole('button',{name:'Check booking status'}).waitFor();assert.equal(await page.evaluate(()=>sessionStorage.getItem('wvd-development-booking-retry-v1')),capability);
 for(const value of records.values())value.conferenceData={createRequest:{status:{statusCode:'success'}},conferenceSolution:{key:{type:'hangoutsMeet'}},entryPoints:[{entryPointType:'video',uri:'https://meet.google.com/abc-defg-hij'}]};
 await page.getByRole('button',{name:'Check booking status'}).click();await page.getByRole('link',{name:'Open Google Meet'}).waitFor();assert.match(await page.locator('#message').textContent(),/^Confirmed:/);assert.equal(inserts,1);assert.equal(await page.evaluate(()=>sessionStorage.getItem('wvd-development-booking-retry-v1')),null);await capture('booking-mobile-confirmed');
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 const secondContext=await browser.newContext({viewport:{width:1280,height:800}}),second=await secondContext.newPage();await second.goto(origin+'/book');await second.getByLabel('Choose a date').fill('2026-10-06');await second.getByRole('button',{name:'Find available times'}).click();await second.getByRole('button',{name:'09:00',exact:true}).click();await second.getByRole('button',{name:'Confirm this time'}).click();await second.waitForFunction(()=>document.getElementById('message').textContent.startsWith('That time is no longer available.'));assert.equal(inserts,1);assert.equal(await second.getByLabel('Choose a date').isDisabled(),false);
 if(evidence)await second.screenshot({path:join(evidence,'booking-desktop-unavailable.png'),fullPage:true,scale:'css',animations:'disabled'});
 // Simulate a connection lost after the server has created the event. The UI
 // must retain its capability and recover without another insert.
 await second.getByLabel('Choose a date').fill('2026-10-07');await second.getByRole('button',{name:'Find available times'}).click();await second.getByRole('button',{name:'09:00',exact:true}).click();
 await second.route('**/api/calls/book',async route=>{await route.fetch();await route.abort('failed');},{times:1});
 await second.getByRole('button',{name:'Confirm this time'}).click();await second.waitForFunction(()=>document.getElementById('message').textContent.startsWith('The connection was interrupted.'));assert.equal(inserts,2);assert.equal(await second.getByLabel('Choose a date').isDisabled(),true);
 for(const value of records.values())value.conferenceData={createRequest:{status:{statusCode:'success'}},conferenceSolution:{key:{type:'hangoutsMeet'}},entryPoints:[{entryPointType:'video',uri:'https://meet.google.com/abc-defg-hij'}]};
 await second.getByRole('button',{name:'Check booking status'}).click();await second.getByRole('link',{name:'Open Google Meet'}).waitFor();assert.equal(inserts,2);
 await page.getByRole('button',{name:'Cancel this booking',exact:true}).click();await page.getByRole('button',{name:'Keep booking',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Yes, cancel booking',exact:true}).isVisible(),false);assert.equal(records.size,2);
 await page.getByRole('button',{name:'Cancel this booking',exact:true}).click();await page.getByRole('button',{name:'Yes, cancel booking',exact:true}).click();await page.getByRole('button',{name:'Check cancellation status',exact:true}).waitFor();assert.equal(await page.getByLabel('Choose a date').isDisabled(),true);
 const saved=JSON.parse(capability),reservationId=createHash('sha256').update(JSON.stringify([productId,calendarId,saved.requestKey])).digest('hex');const replacement={productId,reservationId:'replacement',start:saved.start,end:new Date(Date.parse(saved.start)+1800000).toISOString()};await assert.rejects(store.reserve(replacement),/BOOKING_SLOT_RESERVED/);
 await page.reload();await page.getByRole('button',{name:'Check cancellation status',exact:true}).waitFor();cancelOutage=false;await page.getByRole('button',{name:'Check cancellation status',exact:true}).click();await page.waitForFunction(()=>document.getElementById('message').textContent.startsWith('This booking has been cancelled.'));assert.equal((await store.read(reservationId)).phase,'CANCELLED');assert.equal(await page.getByLabel('Choose a date').isDisabled(),false);assert.equal(await page.getByRole('link',{name:'Open Google Meet'}).isVisible(),false);assert.equal((await store.reserve(replacement)).phase,'RESERVED');await capture('booking-mobile-cancelled');
 assert.deepEqual(errors,[]);await secondContext.close();await context.close();
});
