import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {FirestoreBookingReservations} from '../booking-reservations.mjs';
import {googleBookingEventId} from '../google-booking-event.mjs';
import {exportBookingBackup,rehearseBookingBackup,rehearseFirestoreBookingBackup} from '../booking-backup.mjs';
test('real Firestore transactions serialize competing bookings and preserve durable ownership',async t=>{
  if(!/^127\.0\.0\.1:\d+$/.test(process.env.FIRESTORE_EMULATOR_HOST??''))throw Error('ISOLATED_EMULATOR_REQUIRED');
  const app=initializeApp({projectId:'demo-wvd-portal'},'booking-'+randomUUID()),db=getFirestore(app);
  t.after(async()=>{await db.terminate();await deleteApp(app);});
  const productId='booking-'+randomUUID(),calendarId=randomUUID()+'@example.test';
  const backupBinding={projectId:'demo-wvd-portal',productId,calendarId,databaseId:'(default)',mode:'emulator'};
  const config={db,productId,calendarId,backupBinding},first=new FirestoreBookingReservations(config),second=new FirestoreBookingReservations(config);
  const value=id=>({productId,reservationId:id,start:'2026-10-06T12:00:00.000Z',end:'2026-10-06T12:30:00.000Z'});
  const attempts=await Promise.allSettled([first.reserve(value('a')),second.reserve(value('b'))]);
  assert.equal(attempts.filter(x=>x.status==='fulfilled').length,1);
  assert.match(attempts.find(x=>x.status==='rejected').reason.message,/BOOKING_SLOT_RESERVED/);
  const held=attempts.find(x=>x.status==='fulfilled').value;
  const claims=await Promise.all([first.beginWrite(held.reservationId),second.beginWrite(held.reservationId)]);
  assert.equal(claims.filter(x=>x.claimed).length,1);
  const claim=claims.find(x=>x.claimed).reservation;
  const result={eventId:googleBookingEventId(productId,calendarId,held.reservationId),status:'EVENT_AND_MEET_READY',meetUrl:'https://meet.google.com/abc-defg-hij'};
  await first.confirm(held.reservationId,claim.claimId,result);
  const reopened=new FirestoreBookingReservations(config);
  assert.equal((await reopened.reserve(value(held.reservationId))).phase,'CONFIRMED');
  const foreign=new FirestoreBookingReservations({...config,productId:'foreign',backupBinding:undefined});
  await assert.rejects(foreign.reserve({...value('foreign'),productId:'foreign'}),/SCHEDULE_OWNERSHIP_CONFLICT/);
  await reopened.beginCancellation(held.reservationId);
  await assert.rejects(second.reserve(value('replacement')),/BOOKING_SLOT_RESERVED/);
  await reopened.confirmCancellation(held.reservationId,{status:'EVENT_ABSENT',eventId:result.eventId},'2026-10-02T12:00:00.000Z');
  assert.equal((await second.read(held.reservationId)).phase,'CANCELLED');
  assert.equal((await second.reserve(value('replacement'))).phase,'RESERVED');
  await second.reserve({...value('uncertain'),start:'2026-10-06T14:00:00.000Z',end:'2026-10-06T14:30:00.000Z'});await second.beginWrite('uncertain');
  const moving={...value('moving'),start:'2026-10-07T12:00:00.000Z',end:'2026-10-07T12:30:00.000Z'};
  await first.reserve(moving);const movingClaim=await first.beginWrite('moving');
  await first.confirm('moving',movingClaim.reservation.claimId,{...result,eventId:googleBookingEventId(productId,calendarId,'moving')});
  await first.attachManagement(moving,{tokenHash:'a'.repeat(64),expiresAt:'2026-10-10T12:00:00.000Z'});
  const move={expectedRevision:0,changeId:'move',start:'2026-10-07T14:00:00.000Z'};
  await first.beginReschedule(moving,move);
  for(const start of [moving.start,move.start])await assert.rejects(second.reserve({...value('move-competitor'),start,end:new Date(Date.parse(start)+1800000).toISOString()}),/BOOKING_SLOT_RESERVED/);
  const movingClaims=await Promise.all([first.claimReschedule('moving','move'),second.claimReschedule('moving','move')]);assert.equal(movingClaims.filter(x=>x.claimed).length,1);
  assert.equal((await reopened.readManaged('moving','a'.repeat(64),'2026-10-04T12:00:00.000Z')).change.phase,'WRITING');
  await assert.rejects(reopened.readManaged('moving','b'.repeat(64),'2026-10-04T12:00:00.000Z'),/MANAGEMENT_DENIED/);
  const before=await second.backupSnapshot(),raw=await exportBookingBackup(second,backupBinding,()=> '2026-10-04T12:00:00.000Z');
  const proof=await rehearseFirestoreBookingBackup(raw,backupBinding);assert.deepEqual(proof,await rehearseBookingBackup(raw,backupBinding));assert.equal(proof.reservations,4);assert.equal(proof.activeHolds,3);assert.equal(proof.cancelled,1);assert.deepEqual(await second.backupSnapshot(),before);
});
