import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getFirestore} from 'firebase-admin/firestore';
import {firebaseConfiguration} from '../firebase-config.mjs';
import {enquiryCollectionId} from '../enquiry.mjs';
import {createFirestoreEnquiryStore} from '../enquiry-firestore.mjs';
import {createEnquiryNotificationDispatcher} from '../enquiry-mail.mjs';

test('real Firestore: enquiry transaction, native expiry, ordered pages, private rules and notification claims',async t => {
  const config = firebaseConfiguration({projectId:'demo-wvd-portal',productId:'enquiry-' + randomUUID(),databaseId:'(default)',mode:'emulator'});
  const app = initializeApp({projectId:config.projectId},'enquiry-test-' + randomUUID()),db = getFirestore(app);
  t.after(async () => {await db.terminate();await deleteApp(app);});
  let instant = '2026-10-06T14:00:00.000Z';
  const clock = () => instant;
  const storeConfig = {db,productId:config.productId,clock,admission:{minuteLimit:10,dailyLimit:50},retentionDays:90};
  const store = createFirestoreEnquiryStore(storeConfig);
  const input = {requestId:randomUUID(),fields:{name:'Synthetic café 😀',business:'Synthetic business',email:'synthetic@example.test',need:'Emulator-only enquiry.',website:'',timing:'',budget:''},websiteTrap:''};
  const duplicates = await Promise.all(Array.from({length:4},() => store.accept(input)));
  assert.equal(duplicates.filter(row => row.created).length,1);
  const id = duplicates[0].receiptId;
  const ref = db.doc(`wvd_products/${config.productId}/${enquiryCollectionId(config.productId)}/${id}`);
  const saved = (await ref.get()).data();
  assert.equal(saved.deleteAt.toDate().toISOString(),'2027-01-04T14:00:00.000Z');
  assert.equal(saved.notification.status,'PENDING');
  assert.equal((await createFirestoreEnquiryStore(storeConfig).accept(input)).created,false);
  await assert.rejects(store.accept({...input,fields:{...input.fields,need:'Changed request'}}),/ENQUIRY_CONFLICT/);
  await Promise.all(Array.from({length:3},() => store.accept({...input,requestId:randomUUID()})));
  const first = await store.list({limit:2}),second = await store.list({limit:2,cursor:first.nextCursor});
  assert.equal(first.enquiries.length,2);assert.equal(second.enquiries.length,2);assert.equal(second.nextCursor,null);
  assert.equal(new Set([...first.enquiries,...second.enquiries].map(row => row.id)).size,4);
  assert.equal((await store.read(id)).fields.name,input.fields.name);
  const otherProductId = 'other-' + randomUUID();
  const other = createFirestoreEnquiryStore({...storeConfig,productId:otherProductId});
  assert.equal(await other.read(id),null);
  await assert.rejects(other.list({cursor:first.nextCursor}),/INVALID_ENQUIRY/);
  const otherAccepted = await other.accept(input);
  const otherRef = db.doc(`wvd_products/${otherProductId}/${enquiryCollectionId(otherProductId)}/${otherAccepted.receiptId}`);
  const otherSaved = (await otherRef.get()).data();
  const genericRef = db.doc(`wvd_products/${config.productId}/enquiries/${id}`);
  await genericRef.set(saved);

  const direct = `http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/${config.projectId}/databases/(default)/documents/wvd_products/${config.productId}/${enquiryCollectionId(config.productId)}/${id}`;
  assert.equal((await fetch(direct)).status,403);
  assert.equal((await fetch(direct,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({fields:{productId:{stringValue:'foreign'}}})})).status,403);

  let sends = 0;
  const notify = createEnquiryNotificationDispatcher({store,clock,sender:{verifyAccess:async () => {},send:async () => {sends++;return {status:'ACCEPTED',receipt:'synthetic-provider-receipt'};}}});
  await Promise.all([notify(id),notify(id)]);
  assert.equal(sends,1);assert.equal((await store.read(id)).notification.status,'ACCEPTED');
  instant = '2027-01-04T14:00:00.000Z';
  assert.deepEqual(await store.cleanup({limit:2}),{deleted:2,hasMore:true});
  assert.equal((await store.list()).enquiries.length,0);
  assert.equal(await store.read(id),null);
  assert.equal((await db.collection(`wvd_products/${config.productId}/${enquiryCollectionId(config.productId)}`).get()).size,0);
  assert.deepEqual((await genericRef.get()).data(),saved);
  assert.deepEqual((await otherRef.get()).data(),otherSaved);
});
