import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {createPortalServer} from '../server.mjs';
import {createFirebaseBackend} from '../firebase-backend.mjs';
const config={projectId:'demo-wvd-portal',productId:'test-'+randomUUID(),databaseId:'(default)',mode:'emulator'};
const fixture=()=>({identities:[{id:'owner',active:true},{id:'member',active:true},{id:'foreign',active:true}],projects:[{id:'p',businessId:'b'},{id:'other',businessId:'other'}],memberships:[{actorId:'owner',businessId:'b',active:true,role:'Owner',projectIds:['p']},{actorId:'member',businessId:'b',active:true,role:'Member',projectIds:['p']},{actorId:'foreign',businessId:'other',active:true,role:'Owner',projectIds:['other']}],milestones:[{id:'m',projectId:'p',currentVersionId:'v',status:'awaiting-client'}]});
const approval={actorId:'owner',projectId:'p',milestoneId:'m',versionId:'v',operationId:'approve'};
const ticket=id=>({actorId:'owner',projectId:'p',type:'question',subject:'Question',body:'Help',operationId:id});
test('real Google emulators: identity, product isolation, concurrent atomic writes, denial and persistence',async t=>{
 const backend=createFirebaseBackend(config);t.after(()=>backend.close());
 const app=initializeApp({projectId:config.projectId},'fixtures-'+randomUUID()),auth=getAuth(app),db=getFirestore(app);
 t.after(async()=>{await db.terminate();await deleteApp(app);});
 assert.deepEqual(await backend.portal.initialize(fixture()),{created:true});
 assert.deepEqual(await backend.portal.initialize(fixture()),{created:false});
 const other=createFirebaseBackend({...config,productId:config.productId+'-other'});t.after(()=>other.close());await other.portal.initialize({...fixture(),identities:fixture().identities.map(x=>({...x,active:false}))});
 const uid='owner';await auth.createUser({uid,email:'owner@example.test',emailVerified:true,password:'Emulator-only-123!'});
 const login=await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'owner@example.test',password:'Emulator-only-123!',returnSecureToken:true})});
 assert.equal(login.status,200);const {idToken}=await login.json();
 assert.deepEqual(await backend.resolveSession(idToken),{actorId:uid});assert.equal(await other.resolveSession(idToken),null);
 await assert.rejects(()=>backend.portal.projectOverview('foreign','p'),/ACCESS_DENIED/);
 await assert.rejects(()=>backend.portal.approve({...approval,actorId:'member'}),/ACCESS_DENIED/);
 const server=createPortalServer({portal:backend.portal,resolveSession:backend.resolveSession,allowedOrigin:'http://localhost'});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const base=`http://127.0.0.1:${server.address().port}`;
 const approved=await fetch(base+'/api/portal/approve',{method:'POST',headers:{authorization:`Bearer ${idToken}`,origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({projectId:'p',milestoneId:'m',versionId:'v',operationId:'approve'})});
 assert.equal(approved.status,200);const saved=await approved.json();assert.deepEqual(await backend.portal.approve(approval),saved);
 await backend.portal.replaceVersion('m','v2');const before=await backend.portal.snapshot();await assert.rejects(()=>backend.portal.approve({...approval,operationId:'stale'}),/VERSION_CONFLICT/);assert.deepEqual(await backend.portal.snapshot(),before);
 await Promise.all(['a','b','c'].map(id=>backend.portal.createTicket(ticket(id))));
 const state=await backend.portal.snapshot();assert.equal(state.tickets.length,3);assert.equal(state.receipts.length,1);assert.equal(state.outbox.length,4);
 const reopened=createFirebaseBackend(config);t.after(()=>reopened.close());assert.deepEqual(await reopened.portal.snapshot(),state);
 await reopened.portal.replaceVersion('m','v3');
 const results=await Promise.allSettled(['first','second'].map(operationId=>backend.portal.approve({...approval,versionId:'v3',operationId})));
 assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/STATE_CONFLICT/);
 await reopened.portal.revokeMembership('owner','b');await assert.rejects(()=>backend.portal.approve(approval),/ACCESS_DENIED/);
 const url=`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/${config.projectId}/databases/(default)/documents/wvd_products/${config.productId}/private/portal-state`;
 for(const headers of [{},{authorization:`Bearer ${idToken}`}]){assert.equal((await fetch(url,{headers})).status,403);assert.equal((await fetch(url,{method:'PATCH',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({fields:{schemaVersion:{integerValue:'1'}}})})).status,403);}
 const tooLarge=createFirebaseBackend({...config,productId:config.productId+'-large'});t.after(()=>tooLarge.close());
 const large=fixture();large.projects[0].description='x'.repeat(600000);await assert.rejects(()=>tooLarge.portal.initialize(large),/STATE_CAPACITY/);
 assert.equal((await db.doc(`wvd_products/${config.productId}-large/private/portal-state`).get()).exists,false);
 await auth.updateUser(uid,{disabled:true});assert.equal(await backend.resolveSession(idToken),null);
 const ref=db.doc(`wvd_products/${config.productId}/private/portal-state`);await ref.update({stateJson:'{broken'});await assert.rejects(()=>backend.portal.snapshot(),/CORRUPT_PORTAL_STATE/);
});
