import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getAuth} from 'firebase-admin/auth';
import {getFirestore} from 'firebase-admin/firestore';
import {createPortalServer} from '../server.mjs';
import {createFirebaseBackend} from '../firebase-backend.mjs';
const config={projectId:'demo-wvd-portal',productId:'test-'+randomUUID(),databaseId:'(default)',mode:'emulator'};
const fixture=()=>({identities:[{id:'owner',active:true},{id:'member',active:true},{id:'foreign',active:true}],projects:[{id:'p',businessId:'b'},{id:'other',businessId:'other'}],memberships:[{actorId:'owner',businessId:'b',active:true,role:'Owner',projectIds:['p']},{actorId:'member',businessId:'b',active:true,role:'Member',projectIds:['p']},{actorId:'foreign',businessId:'other',active:true,role:'Owner',projectIds:['other']}],milestones:[{id:'m',projectId:'p',currentVersionId:'v',status:'awaiting-client'}]});
const approval={actorId:'owner',projectId:'p',milestoneId:'m',versionId:'v',operationId:'approve'};
const ticket=id=>({actorId:'owner',projectId:'p',type:'question',subject:'Question',body:'Help',operationId:id});
test('real Google emulators: identity, product isolation, concurrent atomic writes, denial and persistence',async t=>{
 const backend=createFirebaseBackend(config);t.after(()=>backend.close());
 const app=initializeApp({projectId:config.projectId},'fixtures-'+randomUUID()),auth=getAuth(app),db=getFirestore(app);
 t.after(async()=>{await db.terminate();await deleteApp(app);});
 assert.deepEqual(await backend.portal.initialize(fixture()),{created:true});
 assert.deepEqual(await backend.portal.initialize(fixture()),{created:false});
 const other=createFirebaseBackend({...config,productId:config.productId+'-other'});t.after(()=>other.close());await other.portal.initialize({...fixture(),identities:fixture().identities.map(x=>({...x,active:false}))});
 const uid='owner';await auth.createUser({uid,email:'owner@example.test',emailVerified:true,password:'Emulator-only-123!'});
 const login=await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fake`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:'owner@example.test',password:'Emulator-only-123!',returnSecureToken:true})});
 assert.equal(login.status,200);const {idToken}=await login.json();
 assert.deepEqual(await backend.resolveSession(idToken),{actorId:uid});assert.equal(await other.resolveSession(idToken),null);
 await assert.rejects(()=>backend.portal.projectOverview('foreign','p'),/ACCESS_DENIED/);
 await assert.rejects(()=>backend.portal.approve({...approval,actorId:'member'}),/ACCESS_DENIED/);
 const server=createPortalServer({portal:backend.portal,resolveSession:backend.resolveSession,allowedOrigin:'http://localhost'});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>server.close(resolve)));
 const base=`http://127.0.0.1:${server.address().port}`;
 const approved=await fetch(base+'/api/portal/approve',{method:'POST',headers:{authorization:`Bearer ${idToken}`,origin:'http://localhost','content-type':'application/json'},body:JSON.stringify({projectId:'p',milestoneId:'m',versionId:'v',operationId:'approve'})});
 assert.equal(approved.status,200);const saved=await approved.json();assert.deepEqual(await backend.portal.approve(approval),saved);
 await backend.portal.replaceVersion('m','v2');const before=await backend.portal.snapshot();await assert.rejects(()=>backend.portal.approve({...approval,operationId:'stale'}),/VERSION_CONFLICT/);assert.deepEqual(await backend.portal.snapshot(),before);
 await Promise.all(['a','b','c'].map(id=>backend.portal.createTicket(ticket(id))));
 const state=await backend.portal.snapshot();assert.equal(state.tickets.length,3);assert.equal(state.receipts.length,1);assert.equal(state.outbox.length,4);
 const reopened=createFirebaseBackend(config);t.after(()=>reopened.close());assert.deepEqual(await reopened.portal.snapshot(),state);
 await reopened.portal.replaceVersion('m','v3');
 const results=await Promise.allSettled(['first','second'].map(operationId=>backend.portal.approve({...approval,versionId:'v3',operationId})));
 assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/STATE_CONFLICT/);
 await reopened.portal.revokeMembership('owner','b');await assert.rejects(()=>backend.portal.approve(approval),/ACCESS_DENIED/);
 const url=`http://${process.env.FIRESTORE_EMULATOR_HOST}/v1/projects/${config.projectId}/databases/(default)/documents/wvd_products/${config.productId}/private/portal-state`;
 for(const headers of [{},{authorization:`Bearer ${idToken}`}]){assert.equal((await fetch(url,{headers})).status,403);assert.equal((await fetch(url,{method:'PATCH',headers:{...headers,'content-type':'application/json'},body:JSON.stringify({fields:{schemaVersion:{integerValue:'1'}}})})).status,403);}
 const tooLarge=createFirebaseBackend({...config,productId:config.productId+'-large'});t.after(()=>tooLarge.close());
 const large=fixture();large.projects[0].description='x'.repeat(600000);await assert.rejects(()=>tooLarge.portal.initialize(large),/STATE_CAPACITY/);
 assert.equal((await db.doc(`wvd_products/${config.productId}-large/private/portal-state`).get()).exists,false);
 await auth.updateUser(uid,{disabled:true});assert.equal(await backend.resolveSession(idToken),null);
 const ref=db.doc(`wvd_products/${config.productId}/private/portal-state`);await ref.update({stateJson:'{broken'});await assert.rejects(()=>backend.portal.snapshot(),/CORRUPT_PORTAL_STATE/);
});

test('real browser Firebase emulator sign-in, trusted provisioning, approval and disabled-user denial',async t=>{
 const {chromium}=await import('@playwright/test');
 const {createApplication}=await import('../app.mjs');
 const suffix=randomUUID(),uid='browser-'+suffix,email=uid+'@example.test',password='Synthetic-browser-123!';
 const browserConfig={...config,productId:'browser-'+suffix},backend=createFirebaseBackend(browserConfig);
 t.after(()=>backend.close());
 const state=fixture();state.identities[0].id=uid;state.memberships[0].actorId=uid;
 await backend.portal.initialize(state);
 const review=await backend.portal.publishReview({projectId:'p',milestoneId:'m',versionId:'v',title:'Synthetic design review',body:'Review the heading, navigation and contact form before approving this version.'},0,{operatorRef:'synthetic-test',changeRef:'browser-review'});
 const app=initializeApp({projectId:config.projectId},'browser-fixtures-'+suffix),auth=getAuth(app);
 t.after(()=>deleteApp(app));
 await auth.createUser({uid,email,emailVerified:true,password});
 const unprovisioned='unprovisioned-'+suffix;await auth.createUser({uid:unprovisioned,email:unprovisioned+'@example.test',emailVerified:true,password});
 const origin='http://127.0.0.1:4703',server=createApplication({portal:backend.portal,auth:{resolveSession:backend.resolveSession},allowedOrigin:origin,firebaseEmulator:browserConfig});
 await new Promise(resolve=>server.listen(4703,'127.0.0.1',resolve));
 t.after(async()=>{server.closeIdleConnections();await new Promise(resolve=>server.close(resolve));});
 assert.equal((await fetch(origin+'/api/auth/login',{method:'POST'})).status,404);
 const evidence=process.env.WVD_TEST_EVIDENCE_DIR;
 if(evidence)mkdirSync(evidence,{recursive:true});
 const browser=await chromium.launch(),context=await browser.newContext({viewport:{width:390,height:844},...(evidence?{recordVideo:{dir:evidence,size:{width:390,height:844}}}:{})});
 t.after(async()=>{await context.close();await browser.close();});
 const page=await context.newPage();
 const capture=async name=>{if(evidence)await page.screenshot({path:join(evidence,name+'.png'),fullPage:true});};
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(origin);
 await page.locator('#login').getByLabel('Email').fill(unprovisioned+'@example.test');await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login button').click();
 await page.waitForFunction(()=>document.getElementById('status').textContent==='Please sign in again.');
 assert.equal(await page.locator('#workspace').isVisible(),false);
 const {createFirebaseProvisioner}=await import('../firebase-provisioning.mjs');
 const rawProvision=createFirebaseProvisioner(backend),provision=(request,revision)=>rawProvision(request,revision,{operatorRef:'synthetic-test',changeRef:'browser-grant'}),revision=await backend.portal.accessRevision(),beforeGrant=await backend.portal.snapshot();
 await assert.rejects(()=>provision({uid:unprovisioned,businessId:'b',role:'Member',projectIds:['other']},revision),/PROJECT_SCOPE_DENIED/);
 assert.deepEqual(await backend.portal.snapshot(),beforeGrant);
 const grant={uid:unprovisioned,businessId:'b',role:'Member',projectIds:['p']};
 assert.equal((await provision(grant,revision)).created,true);
 await assert.rejects(()=>provision({...grant,role:'Owner'},revision),/ACCESS_REVISION_CONFLICT/);
 const current=await backend.portal.accessRevision();assert.equal((await provision(grant,current)).created,false);assert.equal(await backend.portal.accessRevision(),current);
 await assert.rejects(()=>provision({...grant,role:'Owner'},current),/ACCESS_ALREADY_PROVISIONED/);
 await page.locator('#login').getByLabel('Email').fill(unprovisioned+'@example.test');await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login button').click();
 await page.getByRole('button',{name:'Approve this version'}).waitFor();
 await page.getByRole('button',{name:'Approve this version'}).click();await page.waitForFunction(()=>document.getElementById('status').textContent==='Your account does not have permission for this action.');
 await page.getByText('Synthetic design review',{exact:true}).waitFor();
 assert.equal((await backend.portal.snapshot()).receipts.length,0);
 await capture('member-approval-denied');
 await page.getByLabel('Feedback',{exact:true}).fill('Synthetic feedback: the navigation is ready.');
 await page.getByRole('button',{name:'Send feedback',exact:true}).click();
 await page.locator('.feedback-record').getByText('Synthetic feedback: the navigation is ready.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await page.locator('#login').getByLabel('Email').fill(email);await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login button').click();
 await page.getByRole('button',{name:'Approve this version'}).waitFor();
 assert.equal(await page.locator('#projects option').count(),1);
 assert.equal(await page.locator('#invite-panel').isVisible(),false);
 await page.getByRole('button',{name:'Approve this version'}).click();
 await page.getByText('m — approved').waitFor();
 assert.equal((await backend.portal.snapshot()).receipts.length,1);
 await page.locator('.feedback-record').getByText('Synthetic feedback: the navigation is ready.',{exact:true}).waitFor();
 assert.equal((await backend.portal.snapshot()).receipts[0].reviewDigest,review.digest);
 const audit=(await backend.portal.snapshot()).operatorAudit;assert.equal(audit.length,2);assert.deepEqual(audit.map(x=>x.action),['publishReview','provisionAccess']);
 await page.getByText('m — version v',{exact:true}).click();
 await page.locator('.approval-record').getByText('Synthetic design review',{exact:true}).waitFor();
 assert.equal(await page.locator('.approval-record').getByText('Review the heading, navigation and contact form before approving this version.',{exact:true}).count(),1);
 await capture('owner-milestone-approved');
 assert.deepEqual(await page.evaluate(()=>[Object.keys(localStorage),Object.keys(sessionStorage)]),[[],[]]);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 assert.equal(await page.locator('#workspace').isVisible(),false);
 await page.locator('#login').getByLabel('Email').fill(email);await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login button').click();
 await page.getByText('m — approved').waitFor();
 await auth.updateUser(uid,{disabled:true});
 await page.getByLabel('Subject').fill('Synthetic question');await page.getByLabel('Details').fill('Synthetic details');await page.getByRole('button',{name:'Send ticket',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('status').textContent==='Please sign in again.');
 assert.equal(await page.locator('#workspace').isVisible(),false);
 assert.equal((await backend.portal.snapshot()).tickets.length,0);
 await capture('disabled-user-signed-out');
 assert.deepEqual(errors,[]);
});
