import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {LocalAuth} from '../auth.mjs';
const password='A long private test passphrase';
function setup(t){const dir=mkdtempSync(join(tmpdir(),'wvd-auth-'));let now=Date.now();const path=join(dir,'auth.sqlite');const auth=new LocalAuth(path,()=>now);t.after(()=>{auth.close();rmSync(dir,{recursive:true,force:true});});return {auth,path,advance:ms=>now+=ms};}
async function account(auth,id='owner',email='owner@example.test',peer='peer') {const invite=auth.invite(id,email);await auth.redeem(invite.invitationToken,password,peer);return invite;}
test('invitation creates no usable password until redeemed; token is single-use',async t=>{const {auth}=setup(t);const invite=auth.invite('owner','OWNER@example.test');await assert.rejects(auth.login('owner@example.test',password,'peer'),/UNAUTHENTICATED/);await auth.redeem(invite.invitationToken,password,'peer');await assert.rejects(auth.redeem(invite.invitationToken,password,'peer'),/INVALID_INVITATION/);const login=await auth.login('owner@example.test',password,'peer');assert.deepEqual(auth.resolveSession(login.sessionToken),{actorId:'owner'});});
test('invitation replacement invalidates the earlier code',async t=>{const {auth}=setup(t);const old=auth.invite('owner','owner@example.test'),fresh=auth.invite('owner','owner@example.test');await assert.rejects(auth.redeem(old.invitationToken,password,'peer'),/INVALID_INVITATION/);await auth.redeem(fresh.invitationToken,password,'peer');});
test('expired invitation is rejected',async t=>{const {auth,advance}=setup(t);const invite=auth.invite('owner','owner@example.test');advance(24*60*60*1000);await assert.rejects(auth.redeem(invite.invitationToken,password,'peer'),/INVALID_INVITATION/);});
test('minimum and bounded passwords are enforced',async t=>{const {auth}=setup(t);const invite=auth.invite('owner','owner@example.test');for(const value of ['short','x'.repeat(1025)])await assert.rejects(auth.redeem(invite.invitationToken,value,'peer'),/INVALID_PASSWORD/);});
test('unknown and incorrect credentials share the same failure',async t=>{const {auth}=setup(t);await account(auth);await assert.rejects(auth.login('owner@example.test','wrong','peer'),/UNAUTHENTICATED/);await assert.rejects(auth.login('unknown@example.test','wrong','peer'),/UNAUTHENTICATED/);});
test('logout revokes exactly the presented session',async t=>{const {auth}=setup(t);await account(auth);const a=await auth.login('owner@example.test',password,'peer'),b=await auth.login('owner@example.test',password,'peer');auth.logout(a.sessionToken);assert.equal(auth.resolveSession(a.sessionToken),null);assert.deepEqual(auth.resolveSession(b.sessionToken),{actorId:'owner'});});
test('account disable revokes sessions and outstanding invitations',async t=>{const {auth}=setup(t);await account(auth);const login=await auth.login('owner@example.test',password,'peer'),invite=auth.invite('owner','owner@example.test');auth.disable('owner');assert.equal(auth.resolveSession(login.sessionToken),null);await assert.rejects(auth.redeem(invite.invitationToken,password,'peer'),/INVALID_INVITATION/);await assert.rejects(auth.login('owner@example.test',password,'peer'),/UNAUTHENTICATED/);assert.throws(()=>auth.invite('owner','owner@example.test'),/ACCESS_DENIED/);});
test('password recovery revokes existing sessions',async t=>{const {auth}=setup(t);await account(auth);const login=await auth.login('owner@example.test',password,'peer'),invite=auth.invite('owner','owner@example.test');await auth.redeem(invite.invitationToken,'A different long private passphrase','peer');assert.equal(auth.resolveSession(login.sessionToken),null);await assert.rejects(auth.login('owner@example.test',password,'peer'),/UNAUTHENTICATED/);await auth.login('owner@example.test','A different long private passphrase','peer');});
test('sessions expire and survive server restart before expiration',async t=>{const {auth,path,advance}=setup(t);await account(auth);const login=await auth.login('owner@example.test',password,'peer');const other=new LocalAuth(path);assert.deepEqual(other.resolveSession(login.sessionToken),{actorId:'owner'});other.close();advance(8*60*60*1000);assert.equal(auth.resolveSession(login.sessionToken),null);});
test('raw passwords, invitations and session tokens are not stored',async t=>{const {auth,path}=setup(t);const invite=await account(auth);const login=await auth.login('owner@example.test',password,'peer');const bytes=readFileSync(path);for(const value of [password,invite.invitationToken,login.sessionToken])assert.equal(bytes.includes(Buffer.from(value)),false);});
test('persistent rate limit is shared across app instances and expires',async t=>{const {auth,path,advance}=setup(t);for(let i=0;i<10;i++)await assert.rejects(auth.login('unknown@example.test','wrong','peer'),/UNAUTHENTICATED/);const other=new LocalAuth(path);await assert.rejects(other.login('another@example.test','wrong','peer'),/RATE_LIMITED/);other.close();advance(15*60*1000);await assert.rejects(auth.login('unknown@example.test','wrong','peer'),/UNAUTHENTICATED/);});
test('parallel redemption accepts an invitation exactly once',async t=>{const {auth}=setup(t);const invite=auth.invite('owner','owner@example.test');const result=await Promise.allSettled([auth.redeem(invite.invitationToken,password,'peer'),auth.redeem(invite.invitationToken,'Another long private passphrase','peer')]);assert.equal(result.filter(x=>x.status==='fulfilled').length,1);assert.equal(result.filter(x=>x.status==='rejected'&&x.reason.message==='INVALID_INVITATION').length,1);});
test('actor email binding cannot be silently changed',t=>{const {auth}=setup(t);auth.invite('owner','owner@example.test');assert.throws(()=>auth.invite('owner','different@example.test'),/ACCOUNT_CONFLICT/);assert.throws(()=>auth.invite('another','owner@example.test'));});
test('malformed bearer tokens fail closed',t=>{const {auth}=setup(t);for(const raw of [undefined,null,{},'wrong','x'.repeat(8193)])assert.equal(auth.resolveSession(raw),null);});
test('disable during password hashing prevents redemption',async t=>{const {auth}=setup(t);const invite=auth.invite('owner','owner@example.test');const pending=auth.redeem(invite.invitationToken,password,'peer');auth.disable('owner');await assert.rejects(pending,/INVALID_INVITATION/);});
test('disable during login prevents session creation',async t=>{const {auth}=setup(t);await account(auth);const pending=auth.login('owner@example.test',password,'peer');auth.disable('owner');await assert.rejects(pending,/UNAUTHENTICATED/);});
test('simultaneous password work has a bounded queue',async t=>{const {auth}=setup(t);const a=auth.login('a@example.test','wrong','peer-a'),b=auth.login('b@example.test','wrong','peer-b');await assert.rejects(auth.login('c@example.test','wrong','peer-c'),/AUTH_BUSY/);await Promise.all([assert.rejects(a,/UNAUTHENTICATED/),assert.rejects(b,/UNAUTHENTICATED/)]);});
test('only five sessions remain usable per account',async t=>{const {auth}=setup(t);await account(auth);const tokens=[];for(let i=0;i<6;i++)tokens.push((await auth.login('owner@example.test',password,'peer')).sessionToken);assert.equal(tokens.filter(raw=>auth.resolveSession(raw)).length,5);});
