import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createBookingManagementHandler} from '../booking-management-http.mjs';
const origin='https://example.test',start='2026-10-06T09:00:00.000Z',end='2026-10-06T09:30:00.000Z',expiresAt='2026-10-07T09:00:00.000Z';
const view={status:'CONFIRMED',start,end,revision:0,timeZone:'Europe/London',meetUrl:'https://meet.google.com/abc-defg-hij',expiresAt,private:'hidden'};
const make=(patch={})=>createBookingManagementHandler({productId:'test',calendarId:'synthetic',allowedOrigin:origin,admit:async()=>true,maxConcurrentRequests:1,management:{issue:async value=>({managementUrl:origin+'/book/manage#'+value.reservation.reservationId+'.'+value.managementKey,expiresAt,private:'hidden'}),read:async()=>view,recover:async()=>view,cancel:async()=>({status:'CANCELLED',private:'hidden'}),reschedule:async()=>({status:'RESCHEDULED',revision:1,private:'hidden'}),...patch.management},...Object.fromEntries(Object.entries(patch).filter(([key])=>key!=='management'))});
async function invoke(handler,path='/read',body={token:'opaque'},patch={}){const req=Object.assign(Readable.from([Buffer.from(typeof body==='string'?body:JSON.stringify(body))]),{url:'/api/calls/manage'+path,method:'POST',headers:{origin,'content-type':'application/json'},socket:{remoteAddress:'127.0.0.1'},...patch});const result={},res={headersSent:false,writeHead(status,headers){result.status=status;result.headers=headers;this.headersSent=true;},end(raw){result.body=JSON.parse(raw);},destroy(){result.destroyed=true;}};await handler(req,res);return result;}
test('management reads expose only current public booking fields and never cache capabilities',async()=>{const result=await invoke(make());assert.equal(result.status,200);const {private:ignored,...expected}=view;assert.deepEqual(result.body,expected);assert.equal(result.headers['Cache-Control'],'no-store');});
test('management origin, exact schemas, URL secrecy and admission are required before service calls',async()=>{let calls=0;const handler=make({management:{read:async()=>{calls++;return view;}}});for(const [body,patch,status]of [[{token:'opaque',productId:'foreign'},{},400],[{token:'opaque'},{url:'/api/calls/manage/read?token=secret'},400],[{token:'opaque'},{method:'GET'},405],[{token:'opaque'},{headers:{origin:'https://foreign.test','content-type':'application/json'}},403],[' '.repeat(1537),{},413]])assert.equal((await invoke(handler,'/read',body,patch)).status,status);assert.equal(calls,0);assert.equal((await invoke(make({admit:async()=>false}))).status,429);});
test('issuance binds a private booking key and never accepts caller-selected expiry or origin',async()=>{let received;const body={requestKey:'af30500f-8a91-4eec-8d89-fbd0cd3e9d45',start,managementKey:'a'.repeat(64)};const handler=make({management:{issue:async value=>{received=value;return {managementUrl:origin+'/book/manage#'+value.reservation.reservationId+'.'+value.managementKey,expiresAt};}}});const result=await invoke(handler,'/issue',body);assert.equal(result.status,200);assert.match(received.reservation.reservationId,/^[a-f0-9]{64}$/);assert.equal(received.reservation.productId,'test');assert.equal((await invoke(handler,'/issue',{...body,expiresAt})).status,400);assert.equal((await invoke(make({management:{issue:async()=>({managementUrl:'https://evil.test',expiresAt})}}),'/issue',body)).status,503);});
test('expired and missing links share the same denial and service errors cannot expose details',async()=>{for(const message of ['MANAGEMENT_DENIED','MANAGEMENT_ALREADY_ISSUED']){const result=await invoke(make({management:{read:async()=>{throw Error(message);}}}));assert.equal(result.status,403);assert.deepEqual(result.body,{error:'MANAGEMENT_DENIED'});}const result=await invoke(make({management:{read:async()=>{throw Error('private secret');}}}));assert.deepEqual(result.body,{error:'SERVICE_UNAVAILABLE'});});
test('managed cancellation and rescheduling bind the expected revision and return bounded acknowledgements',async()=>{const cancellation=await invoke(make(),'/cancel',{token:'opaque',start,revision:0});assert.deepEqual(cancellation.body,{status:'CANCELLED'});let call;const handler=make({management:{reschedule:async value=>{call=value;return {status:'RESCHEDULED',revision:1};}}});const body={token:'opaque',start,revision:0,targetStart:'2026-10-06T11:00:00.000Z',changeKey:'bd7a589d-c542-4ff2-bca5-a28feb234b10'};assert.deepEqual((await invoke(handler,'/reschedule',body)).body,{status:'RESCHEDULED',revision:1});assert.match(call.changeId,/^[a-f0-9]{64}$/);assert.equal(call.revision,0);assert.equal((await invoke(handler,'/reschedule',{...body,revision:-1})).status,400);assert.equal((await invoke(make({management:{reschedule:async()=>({status:'RESCHEDULED',revision:7})}}),'/reschedule',body)).status,503);});
test('recovery exposes only the authenticated pending operation and validates recovery inputs',async()=>{const handler=make({management:{read:async()=>({...view,status:'PENDING',pendingAction:{kind:'reschedule',id:'change-one'}})}});const result=await invoke(handler);assert.equal(result.status,200);assert.deepEqual(result.body.pendingAction,{kind:'reschedule',id:'change-one'});assert.equal(Object.hasOwn(result.body,'meetUrl'),false);assert.equal((await invoke(make(),'/recover',{token:'opaque',revision:0,actionId:'change-one'})).status,200);assert.equal((await invoke(make(),'/recover',{token:'opaque',revision:0,actionId:'../foreign'})).status,400);});
test('managed picker is optional, bounded and whitelists only requested replacement slots',async()=>{
 const target='2026-10-06T09:15:00.000Z',slot={start:target,end:'2026-10-06T09:45:00.000Z',timeZone:'Europe/London',private:'hidden'};
 const body={token:'opaque',start,revision:0,starts:[target]};let received;
 assert.equal((await invoke(make(),'/availability',body)).status,404);
 const handler=make({management:{availability:async value=>{received=value;return {provisional:true,slots:[slot]};}}});
 const result=await invoke(handler,'/availability',body);assert.equal(result.status,200);assert.deepEqual(received,body);assert.deepEqual(result.body,{provisional:true,slots:[{start:target,end:slot.end,timeZone:slot.timeZone}]});assert.equal(result.headers['Cache-Control'],'no-store');
 for(const slots of [[slot,slot],[{...slot,start}],[{...slot,timeZone:'UTC'}],[{...slot,end:start}]])assert.equal((await invoke(make({management:{availability:async()=>({provisional:true,slots})}}),'/availability',body)).status,503);
 assert.equal((await invoke(handler,'/availability',{...body,starts:[target,target]})).status,400);assert.equal((await invoke(handler,'/availability',{...body,calendarId:'foreign'})).status,400);
});
test('link lifecycle routes are optional, schema-bound and expose no internal operation metadata',async()=>{
 const token='booking.'+'a'.repeat(64),body={token,managementKey:'b'.repeat(64),rotationKey:'af30500f-8a91-4eec-8d89-fbd0cd3e9d45'};let received;
 assert.equal((await invoke(make(),'/replace',body)).status,404);
 const handler=make({management:{replace:async value=>{received=value;return {managementUrl:origin+'/book/manage#booking.'+value.managementKey,expiresAt,internal:'hidden'};},revoke:async()=>({status:'REVOKED',internal:'hidden'})}});
 const replaced=await invoke(handler,'/replace',body);assert.equal(replaced.status,200);assert.match(received.operationId,/^[a-f0-9]{64}$/);assert.deepEqual(Object.keys(replaced.body).sort(),['expiresAt','managementUrl']);
 assert.deepEqual((await invoke(handler,'/revoke',{token})).body,{status:'REVOKED'});assert.equal((await invoke(handler,'/replace',{...body,expiresAt})).status,400);assert.equal((await invoke(handler,'/revoke',{token,calendarId:'foreign'})).status,400);
});
