import test from 'node:test';
import assert from 'node:assert/strict';
import {createIntroCallScreening} from '../call-screening.mjs';
import {createGoogleCallEvidenceReader} from '../google-calendar-evidence.mjs';
const observed='2026-10-01T08:00:00.000Z',starts=['2026-10-02T16:30:00.000Z','2026-10-02T08:00:00.000Z'];
const policy={ref:'synthetic-screening',bufferBoundary:'between-events',maxEvidenceAgeMs:60000};
const holidays={bankHolidayRegion:'england-and-wales',coveredFrom:'2026-01-01',coveredThrough:'2026-12-31',bankHolidays:[],sourceRef:'synthetic-source'};
function fixture({after=observed,fail=false}={}){let calls=0,request;const readEvidence=createGoogleCallEvidenceReader({calendarIds:['synthetic-main'],clock:()=>observed,maxQueryWindowMs:86400000,requestTimeoutMs:10000,calendar:{freebusy:{query:async(input,options)=>{calls++;request={input,options};if(fail)throw Error('private provider detail');return {data:{kind:'calendar#freeBusy',timeMin:input.requestBody.timeMin,timeMax:input.requestBody.timeMax,calendars:{'synthetic-main':{busy:[]}}}};}}}});return {screen:createIntroCallScreening({readEvidence,clock:()=>after,policy}),calls:()=>calls,request:()=>request};}
test('one bounded Google query covers all 30 minute candidates with both 15 minute margins and strips private evidence',async()=>{const f=fixture(),result=await f.screen({starts,holidayEvidence:holidays});assert.equal(f.calls(),1);assert.equal(f.request().input.requestBody.timeMin,'2026-10-02T07:45:00.000Z');assert.equal(f.request().input.requestBody.timeMax,'2026-10-02T17:15:00.000Z');assert.deepEqual(f.request().options,{timeout:10000,retry:false});assert.equal(result.provisional,true);assert.deepEqual(result.slots.map(x=>x.start),[...starts].sort());assert.equal(JSON.stringify(result).includes('synthetic-main'),false);assert.equal(JSON.stringify(result).includes('policy'),false);});
test('delayed responses, provider failure and bank holidays offer no slots',async()=>{assert.deepEqual((await fixture({after:'2026-10-01T08:02:00.000Z'}).screen({starts,holidayEvidence:holidays})).slots,[]);assert.deepEqual((await fixture({fail:true}).screen({starts,holidayEvidence:holidays})).slots,[]);assert.deepEqual((await fixture().screen({starts,holidayEvidence:{...holidays,bankHolidays:['2026-10-02']}})).slots,[]);});
test('empty/malformed requests and unbound policy cannot cause a provider query',async()=>{const f=fixture();assert.deepEqual(await f.screen({starts:[],holidayEvidence:holidays}),{slots:[],provisional:true});await assert.rejects(()=>f.screen({starts:[starts[0],starts[0]],holidayEvidence:holidays}),/INVALID_BOOKING_INPUT/);assert.equal(f.calls(),0);assert.throws(()=>createIntroCallScreening({readEvidence:async()=>assert.fail(),clock:()=>observed,policy:{...policy,ref:''}}),/INVALID_CONFIGURATION/);});
test('upstream failures are sanitised',async()=>{const screen=createIntroCallScreening({clock:()=>observed,policy,readEvidence:async()=>{throw Error('private credential');}});await assert.rejects(()=>screen({starts,holidayEvidence:holidays}),error=>error.message==='CALL_EVIDENCE_UNAVAILABLE');});
test('caller mutations cannot change in-flight candidates or bound age/buffer policy',async()=>{const input=[...starts],mutablePolicy={...policy};const screen=createIntroCallScreening({clock:()=>observed,policy:mutablePolicy,readEvidence:async window=>{input.splice(0,input.length);mutablePolicy.maxEvidenceAgeMs=0;mutablePolicy.bufferBoundary='inside-hours';return {complete:true,observedAt:'2026-10-01T07:59:30.000Z',requiredCalendarIds:['synthetic-main'],calendars:[{id:'synthetic-main',status:'ok',busy:[],coveredStart:window.coveredStart,coveredEnd:window.coveredEnd}],...holidays};}});const result=await screen({starts:input,holidayEvidence:holidays});assert.equal(result.slots.length,2);assert.deepEqual(result.slots.map(x=>x.start),[...starts].sort());});
test('past, short-notice, weekend, outside-hours, uncovered and holiday candidates cannot trigger a provider read',async()=>{
  const screen=createIntroCallScreening({clock:()=>observed,policy,readEvidence:async()=>assert.fail('ineligible candidates must not query Calendar')});
  for(const input of [{starts:['2026-09-30T08:00:00.000Z']},{starts:['2026-10-01T16:00:00.000Z']},{starts:['2026-10-03T08:00:00.000Z']},{starts:['2026-10-02T07:00:00.000Z']},{starts,holidayEvidence:{...holidays,coveredThrough:'2026-10-01'}},{starts,holidayEvidence:{...holidays,bankHolidays:['2026-10-02']}}])assert.deepEqual(await screen({holidayEvidence:holidays,...input}),{slots:[],provisional:true});
});
test('preflight eligible candidates still lose eligibility when provider delay crosses the notice boundary',async()=>{
  let tick=0;const screen=createIntroCallScreening({policy,clock:()=>tick++===0?observed:'2026-10-01T08:00:01.000Z',readEvidence:async input=>({complete:true,observedAt:observed,requiredCalendarIds:['synthetic-main'],calendars:[{id:'synthetic-main',status:'ok',busy:[],coveredStart:input.coveredStart,coveredEnd:input.coveredEnd}],...holidays})});
  assert.deepEqual(await screen({starts:[starts[1]],holidayEvidence:holidays}),{slots:[],provisional:true});
});
test('mixed candidates narrow provider coverage to eligible slots and preserve both conflict margins',async()=>{
  const f=fixture(),result=await f.screen({starts:['2026-09-01T08:00:00.000Z',starts[0],'2026-10-03T08:00:00.000Z'],holidayEvidence:holidays});
  assert.deepEqual(result.slots.map(x=>x.start),[starts[0]]);assert.equal(f.calls(),1);assert.equal(f.request().input.requestBody.timeMin,'2026-10-02T16:15:00.000Z');assert.equal(f.request().input.requestBody.timeMax,'2026-10-02T17:15:00.000Z');
});
