import test from 'node:test';
import assert from 'node:assert/strict';
import {DurablePortal} from '../durable.mjs';
import {createBoundary} from '../boundary.mjs';
import {createFirebaseColleagueAccessUpdater} from '../firebase-provisioning.mjs';
const state=()=>({identities:[{id:'o',active:true},{id:'m',active:true},{id:'admin',active:true,wvdAdmin:true}],projects:[{id:'p',businessId:'b'},{id:'private-project',businessId:'b'},{id:'foreign',businessId:'other'}],memberships:[{actorId:'o',businessId:'b',role:'Owner',active:true,projectIds:['p']},{actorId:'m',businessId:'b',role:'Member',active:true,projectIds:['p','private-project']},{actorId:'m',businessId:'other',role:'Owner',active:true,projectIds:['foreign']}],milestones:[]});
const input={actorId:'o',projectId:'p',uid:'m',grant:false,expectedRevision:0},clock=()=> '2026-10-03T10:00:00Z';
const verified={uid:'m',disabled:false,emailVerified:true,email:'m@example.test',providerData:[{providerId:'password'}]};
test('Owner removes only selected project access and records atomic audit while preserving other projects/business roles',()=>{
 const portal=new DurablePortal(':memory:',state(),clock);try{const before=portal.snapshot();assert.equal(portal.updateColleagueAccess(input).changed,true);const after=portal.snapshot();assert.deepEqual(after.memberships[1].projectIds,['private-project']);assert.deepEqual(after.memberships[2],before.memberships[2]);assert.equal(after.memberships[1].active,true);assert.equal(after.memberships[1].role,'Member');assert.equal(after.operatorAudit[0].operatorRef,'o');assert.equal(after.operatorAudit[0].changeRef,'owner-project-access');assert.deepEqual(after.operatorAudit[0].previousProjectIds,['p','private-project']);assert.equal(portal.colleaguesFor('o','p').revision,1);assert.throws(()=>portal.updateColleagueAccess(input),/ACCESS_REVISION_CONFLICT/);}finally{portal.close();}
});
test('Colleague list omits Owner/admin accounts, other-business memberships and hidden project grants',()=>{
 const portal=new DurablePortal(':memory:',state(),clock);try{const list=portal.colleaguesFor('o','p');assert.deepEqual(list.accounts,[{accountId:'m',identityActive:true,membershipActive:true,hasProjectAccess:true}]);assert.equal(JSON.stringify(list).includes('private-project'),false);assert.equal(JSON.stringify(list).includes('foreign'),false);assert.equal(JSON.stringify(list).includes('wvdAdmin'),false);for(const actor of ['m','admin','missing'])assert.throws(()=>portal.colleaguesFor(actor,'p'),/ACCESS_DENIED/);}finally{portal.close();}
});
test('Only an active granted Owner may change an existing Member in that client',()=>{
 const portal=new DurablePortal(':memory:',state(),clock);try{const before=portal.snapshot();for(const [patch,error] of [[{actorId:'m'},'ACCESS_DENIED'],[{actorId:'admin'},'ACCESS_DENIED'],[{projectId:'private-project'},'ACCESS_DENIED'],[{projectId:'foreign'},'ACCESS_DENIED'],[{uid:'o'},'ACCESS_ROLE_CONFLICT'],[{uid:'missing'},'ACCESS_MEMBERSHIP_REQUIRED'],[{role:'Owner'},'INVALID_ACCESS_GRANT']])assert.throws(()=>portal.updateColleagueAccess({...input,...patch}),new RegExp(error));assert.deepEqual(portal.snapshot(),before);}finally{portal.close();}
 const revoked=state();revoked.memberships[0].active=false;const portal2=new DurablePortal(':memory:',revoked,clock);try{assert.throws(()=>portal2.updateColleagueAccess(input),/ACCESS_DENIED/);}finally{portal2.close();}
});
test('Owner HTTP mutation returns only selected-project result; schema, origin and stale revision remain enforced',async()=>{
 const portal=new DurablePortal(':memory:',state(),clock);try{const handle=createBoundary({portal,resolveSession:async token=>token?{actorId:token}:null,allowedOrigin:'https://portal.example'}),{actorId,...body}=input;const call=patch=>handle({action:'update-colleague-access',method:'POST',origin:'https://portal.example',sessionToken:'o',rawBody:JSON.stringify(body),...patch});for(const [patch,status] of [[{sessionToken:'m'},403],[{sessionToken:null},401],[{origin:'https://evil.example'},403],[{rawBody:JSON.stringify({...body,actorId:'o'})},400],[{rawBody:JSON.stringify({...body,grant:'false'})},400],[{rawBody:JSON.stringify({...body,expectedRevision:'0'})},400]])assert.equal((await call(patch)).status,status);assert.deepEqual((await call({})).data,{changed:true,accountId:'m',projectId:'p',hasProjectAccess:false});assert.equal((await call({})).status,409);assert.equal((await call({action:'colleague-access-grant',method:'GET'})).status,404);}finally{portal.close();}
});
test('Google Owner workflow checks fresh target only when adding a grant; disabled/deleted account removals need no Auth read',async()=>{
 const portal=new DurablePortal(':memory:',state(),clock);let reads=0;try{const update=createFirebaseColleagueAccessUpdater({portal,auth:{getUser:async()=>{reads++;return verified;}}});await update(input);assert.equal(reads,0);await update({...input,grant:true,expectedRevision:1});assert.equal(reads,1);assert.deepEqual(portal.snapshot().memberships[1].projectIds,['p','private-project']);assert.equal(portal.snapshot().operatorAudit.at(-1).operatorRef,'o');}finally{portal.close();}
});
test('Google Owner workflow rejects unverified targets and stale/revoked delegation without partial grants',async()=>{
 const portal=new DurablePortal(':memory:',state(),clock);try{portal.updateColleagueAccess(input);const before=portal.snapshot();const update=createFirebaseColleagueAccessUpdater({portal,auth:{getUser:async()=>({...verified,emailVerified:false})}});await assert.rejects(()=>update({...input,grant:true,expectedRevision:1}),/VERIFIED_FIREBASE_USER_REQUIRED/);await assert.rejects(()=>update({...input,actorId:'admin',grant:true,expectedRevision:1}),/ACCESS_DENIED/);assert.deepEqual(portal.snapshot(),before);}finally{portal.close();}
});

test('Owner loss during the target Auth read is rechecked before commit',async()=>{
 const portal=new DurablePortal(':memory:',state(),clock);try{portal.updateColleagueAccess(input);const update=createFirebaseColleagueAccessUpdater({portal,auth:{getUser:async()=>{portal.revokeMembership('o','b');return verified;}}});await assert.rejects(()=>update({...input,grant:true,expectedRevision:1}),/ACCESS_DENIED/);assert.deepEqual(portal.snapshot().memberships[1].projectIds,['private-project']);assert.equal(portal.snapshot().operatorAudit.length,1);}finally{portal.close();}
});
