import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createGoogleBookingCancellation} from '../google-booking-cancellation.mjs';
import {googleBookingEventId,createGoogleBookingCalendarClient} from '../google-booking-event.mjs';
const productId='synthetic-product',calendarId='synthetic-calendar',reservation={productId,reservationId:'r',start:'2026-10-06T09:00:00.000Z',end:'2026-10-06T09:30:00.000Z'},eventId=googleBookingEventId(productId,calendarId,'r'),meetUrl='https://meet.google.com/abc-defg-hij';
const confirmation={status:'EVENT_AND_MEET_READY',eventId,meetUrl};
const fixture=()=>({id:eventId,status:'confirmed',etag:'"version-1"',summary:'WVD introductory call',visibility:'private',transparency:'opaque',start:{dateTime:reservation.start},end:{dateTime:reservation.end},extendedProperties:{private:{wvdProduct:productId,wvdReservation:'r',wvdBinding:createHash('sha256').update(JSON.stringify(reservation)).digest('hex')}},conferenceData:{createRequest:{status:{statusCode:'success'}},conferenceSolution:{key:{type:'hangoutsMeet'}},entryPoints:[{entryPointType:'video',uri:meetUrl}]}});
function setup({value=fixture(),remove,read}={}){let current=value,deletes=0,reads=0;const calendar={events:{get:async()=>{reads++;if(read)return read(reads,current);if(!current)throw {response:{status:404}};return {data:structuredClone(current)};},delete:async(params,options)=>{deletes++;assert.deepEqual(params,{calendarId,eventId,sendUpdates:'none'});assert.equal(options.headers['If-Match'],'"version-1"');assert.equal(options.retry,false);if(remove)return remove(()=>{current=null;});current=null;}}};return {cancel:createGoogleBookingCancellation({calendar,calendarId,productId,requestTimeoutMs:1000}),counts:()=>({reads,deletes})};}
test('owned unchanged event is conditionally deleted and absence verified',async()=>{const f=setup();assert.deepEqual(await f.cancel({reservation,confirmation}),{status:'EVENT_ABSENT',eventId});assert.deepEqual(f.counts(),{reads:2,deletes:1});assert.equal((await f.cancel({reservation,confirmation})).status,'EVENT_ABSENT');assert.equal(f.counts().deletes,1);});
test('ambiguous deletion only resolves when a subsequent read proves absence',async()=>{for(const removed of [true,false]){const f=setup({remove:clear=>{if(removed)clear();throw Error('timeout');}});assert.equal((await f.cancel({reservation,confirmation})).status,removed?'EVENT_ABSENT':'CANCELLATION_PENDING');assert.equal(f.counts().deletes,1);}const f=setup({read:async count=>{if(count===1)return {data:fixture()};throw Error('private outage');}});assert.equal((await f.cancel({reservation,confirmation})).status,'CANCELLATION_PENDING');});
test('changed binding, attendees, Meet or missing etag cannot be deleted',async()=>{for(const mutate of [v=>({...v,summary:'foreign'}),v=>({...v,attendees:[{email:'private@example.test'}]}),v=>({...v,etag:undefined}),v=>({...v,etag:'*'}),v=>({...v,conferenceData:{}})]){const f=setup({value:mutate(fixture())});assert.equal((await f.cancel({reservation,confirmation})).status,'CANCELLATION_BLOCKED');assert.equal(f.counts().deletes,0);}});
test('read outages and conditional conflicts retain the hold, without blind retries',async()=>{const f=setup({remove:()=>{throw {response:{status:412}};}});assert.equal((await f.cancel({reservation,confirmation})).status,'CANCELLATION_PENDING');assert.deepEqual(f.counts(),{reads:2,deletes:1});const outage=setup({read:async()=>{throw {response:{status:403}};}});assert.equal((await outage.cancel({reservation,confirmation})).status,'CANCELLATION_PENDING');assert.equal(outage.counts().deletes,0);});
test('only durable matching confirmation is accepted',async()=>{const f=setup();await assert.rejects(f.cancel({reservation,confirmation:{...confirmation,eventId:'foreign'}}),/INVALID_EVENT_CONFIRMATION/);assert.equal(f.counts().reads,0);});
test('fixed-calendar bridge bounds conditional delete and rejects notification or header injection',async()=>{
 const calls=[],client=createGoogleBookingCalendarClient({calendarId,authClient:{request:async options=>{calls.push(options);return {status:204,data:''};}}});
 const params={calendarId,eventId,sendUpdates:'none'},options={timeout:1000,retry:false,headers:{'If-Match':'"version-1"'}};
 await client.events.delete(params,options);assert.equal(calls[0].method,'DELETE');assert.equal(calls[0].url,`https://www.googleapis.com/calendar/v3/calendars/${calendarId}/events/${eventId}`);assert.deepEqual(calls[0].params,{sendUpdates:'none'});assert.deepEqual(calls[0].headers,{'If-Match':'"version-1"'});assert.equal(calls[0].maxRedirects,0);assert.equal(calls[0].retry,false);
 for(const [p,o]of [[{...params,calendarId:'foreign'},options],[{...params,sendUpdates:'all'},options],[params,{...options,headers:{'If-Match':'*'}}],[params,{...options,headers:{'If-Match':'"version-1"',Authorization:'private'}}]])assert.throws(()=>client.events.delete(p,o),/INVALID_CONFIGURATION/);assert.equal(calls.length,1);
});
