import test from 'node:test';
import assert from 'node:assert/strict';
import {createGoogleCallEvidenceReader} from '../google-calendar-evidence.mjs';
import {screenIntroCallCandidates} from '../booking.mjs';
const start='2026-10-02T07:45:00.000Z',end='2026-10-02T17:15:00.000Z',now='2026-10-01T08:00:00.000Z';
const holidays={bankHolidayRegion:'england-and-wales',coveredFrom:'2026-01-01',coveredThrough:'2026-12-31',bankHolidays:[],sourceRef:'synthetic-holiday-fixture'};
const data=()=>({kind:'calendar#freeBusy',timeMin:start,timeMax:end,calendars:{main:{busy:[]},personal:{busy:[]}}});
function reader(query,patch={}){return createGoogleCallEvidenceReader({calendar:{freebusy:{query}},calendarIds:['personal','main'],clock:()=>now,maxQueryWindowMs:86400000,...patch});}
const input=()=>({coveredStart:start,coveredEnd:end,holidayEvidence:structuredClone(holidays)});
const screen=evidence=>screenIntroCallCandidates({now,starts:['2026-10-02T08:00:00.000Z','2026-10-02T16:30:00.000Z'],policy:{bufferBoundary:'between-events',maxEvidenceAgeMs:60000},evidence});
test('Google query includes all explicit calendars and exact coverage; empty busy is free only inside proven coverage',async()=>{let call;const evidence=await reader(async request=>{call=request;return {data:data()};})(input());assert.deepEqual(call.requestBody,{timeMin:start,timeMax:end,timeZone:'UTC',items:[{id:'main'},{id:'personal'}]});assert.equal(evidence.complete,true);assert.equal(evidence.observedAt,now);assert.equal(screen(evidence).length,2);});
test('provider offsets normalise and personal-calendar conflicts remain governed by shared 15 minute buffers',async()=>{const reply=data();reply.calendars.personal.busy=[{start:'2026-10-02T09:00:00+01:00',end:'2026-10-02T09:30:00+01:00',summary:'Private event title'}];const evidence=await reader(async()=>({data:reply}))(input());assert.deepEqual(evidence.calendars.find(x=>x.id==='personal').busy,[{start:'2026-10-02T08:00:00.000Z',end:'2026-10-02T08:30:00.000Z'}]);assert.equal(JSON.stringify(evidence).includes('Private'),false);assert.deepEqual(screen(evidence).map(x=>x.start),['2026-10-02T16:30:00.000Z']);});
test('missing, errored, grouped, narrowed or malformed responses never become free calendars',async()=>{for(const alter of [r=>delete r.calendars.personal,r=>r.kind='events',r=>r.groups=[],r=>r.calendars.personal.errors=[{reason:'notFound',private:'detail'}],r=>r.timeMin='2026-10-02T08:00:00Z',r=>r.groups={group:{calendars:['main']}},r=>r.calendars.main.busy=[{start:'2026-02-30T09:00:00Z',end:'2026-03-02T10:00:00Z'}],r=>r.calendars.main.busy=[{start:'2026-10-02T08:00:00Z',end:'2026-10-02T08:00:00Z'}]]){const reply=data();alter(reply);const evidence=await reader(async()=>({data:reply}))(input());assert.equal(evidence.complete,false);assert.deepEqual(screen(evidence),[]);assert.equal(JSON.stringify(evidence).includes('detail'),false);}});
test('API outages return unavailable evidence and query time remains conservative through delayed calls',async()=>{let observed=now;const evidence=await reader(async()=>{observed='2026-10-01T08:05:00.000Z';return {data:data()};},{clock:()=>observed})(input());assert.equal(evidence.observedAt,now);assert.deepEqual(screenIntroCallCandidates({now:observed,starts:['2026-10-02T16:30:00.000Z'],policy:{bufferBoundary:'between-events',maxEvidenceAgeMs:60000},evidence}),[]);const failed=await reader(async()=>{throw Error('private credential detail');})(input());assert.deepEqual(screen(failed),[]);assert.equal(JSON.stringify(failed).includes('credential'),false);});
test('explicit bounded configuration and verified holiday input are required before any provider read',async()=>{for(const patch of [{calendarIds:[]},{calendarIds:['main','main']},{maxQueryWindowMs:undefined},{clock:undefined}])assert.throws(()=>reader(async()=>assert.fail('no provider call'),patch),/INVALID_CONFIGURATION/);let reads=0;const read=reader(async()=>{reads++;return {data:data()};});for(const patch of [{coveredEnd:start},{coveredStart:'2026-10-02T08:00:00'},{holidayEvidence:{...holidays,bankHolidayRegion:'scotland'}},{holidayEvidence:{...holidays,bankHolidays:['2026-02-30']}},{holidayEvidence:{...holidays,sourceRef:''}}])await assert.rejects(()=>read({...input(),...patch}));assert.equal(reads,0);});

test('configuration and holiday evidence are copied so caller mutation cannot broaden an in-flight query',async()=>{const ids=['main','personal'],request=input();const before=structuredClone(request);const read=reader(async()=>({data:data()}),{calendarIds:ids});ids.push('unreviewed-calendar');const evidence=await read(request);assert.deepEqual(evidence.requiredCalendarIds,['main','personal']);assert.deepEqual(request,before);evidence.requiredCalendarIds.push('unreviewed-calendar');assert.deepEqual((await read(request)).requiredCalendarIds,['main','personal']);});
