import test from 'node:test';
import assert from 'node:assert/strict';
import {PortalProof} from '../domain.mjs';
import {planNotification,createNotificationPlanner} from '../notification-plan.mjs';
const policy={ref:'synthetic-notification-policy',productId:'synthetic-wvd',adminEmail:'admin@example.test',portalOrigin:'https://portal.example.test',clientAudience:'ticket-participants'};
function fixture(){return new PortalProof({identities:[{id:'owner',active:true},{id:'member',active:true},{id:'silent',active:true},{id:'foreign',active:true},{id:'admin',active:true,wvdAdmin:true}],projects:[{id:'p',businessId:'b'},{id:'other',businessId:'different'}],memberships:[{actorId:'owner',businessId:'b',role:'Owner',active:true,projectIds:['p']},{actorId:'member',businessId:'b',role:'Member',active:true,projectIds:['p']},{actorId:'silent',businessId:'b',role:'Member',active:true,projectIds:['p']},{actorId:'foreign',businessId:'different',role:'Owner',active:true,projectIds:['other']}],milestones:[{id:'m',projectId:'p',currentVersionId:'v',status:'awaiting-client'}]},()=> '2026-10-03T11:00:00.000Z');}
const ticket=portal=>portal.createTicket({actorId:'owner',projectId:'p',type:'question',subject:'Private subject',body:'Private support content',operationId:'ticket'});
test('approval and feedback plan only the explicitly configured admin; no portal content leaks into a plan',()=>{const portal=fixture(),approval=portal.approve({actorId:'owner',projectId:'p',milestoneId:'m',versionId:'v',operationId:'approval'}),feedback=portal.submitFeedback({actorId:'member',projectId:'p',milestoneId:'m',versionId:'v',body:'Private feedback',operationId:'feedback'}),before=portal.snapshot();for(const id of [approval.id,feedback.id]){const plan=planNotification(before,id,policy);assert.equal(plan.adminEmail,policy.adminEmail);assert.deepEqual(plan.clientActorIds,[]);assert.equal(plan.portalUrl,policy.portalOrigin+'/');assert.equal(plan.productId,policy.productId);assert.equal(JSON.stringify(plan).includes('Private feedback'),false);}assert.deepEqual(portal.snapshot(),before);});
test('ticket participant policy selects active conversation accounts, excludes other tenants and never grants admin a client recipient',()=>{const portal=fixture(),created=ticket(portal);let plan=planNotification(portal.snapshot(),created.id,policy);assert.deepEqual(plan.clientActorIds,['owner']);const reply=portal.replyToTicket({actorId:'member',projectId:'p',ticketId:created.id,body:'Private reply',operationId:'reply'});portal.replyToTicket({actorId:'admin',projectId:'p',ticketId:created.id,body:'Admin reply',operationId:'admin-reply'});plan=planNotification(portal.snapshot(),reply.id,policy);assert.deepEqual(plan.clientActorIds,['member','owner']);assert.equal(JSON.stringify(plan).includes('Private'),false);assert.equal(JSON.stringify(plan).includes('foreign'),false);});
test('project audience is a separate explicit policy and fresh revocations/grant removal exclude recipients',()=>{const portal=fixture(),created=ticket(portal),projectPolicy={...policy,clientAudience:'project-members'};assert.deepEqual(planNotification(portal.snapshot(),created.id,projectPolicy).clientActorIds,['member','owner','silent']);portal.revokeMembership('silent','b');portal.updateAccess({uid:'member',businessId:'b',role:'Member',projectIds:[]});assert.deepEqual(planNotification(portal.snapshot(),created.id,projectPolicy).clientActorIds,['owner']);const state=portal.snapshot();state.identities.find(x=>x.id==='owner').active=false;assert.deepEqual(planNotification(state,created.id,projectPolicy).clientActorIds,[]);});
test('missing, ambiguous or unsafe policies and damaged intent references fail closed without delivery',()=>{const portal=fixture(),created=ticket(portal),state=portal.snapshot();for(const bad of [undefined,{...policy,clientAudience:undefined},{...policy,portalOrigin:'http://portal.example.test'},{...policy,portalOrigin:'https://portal.example.test/private'},{...policy,adminEmail:'admin@example.test\r\nBcc: foreign@example.test'},{...policy,sender:'invented'}])assert.throws(()=>planNotification(state,created.id,bad),/NOTIFICATION_POLICY_REQUIRED/);assert.throws(()=>planNotification(state,'missing',policy),/INVALID_NOTIFICATION/);const broken=structuredClone(state);broken.outbox[0].receiptId='missing';assert.throws(()=>planNotification(broken,created.id,policy),/CORRUPT_PORTAL_STATE/);assert.deepEqual(portal.snapshot(),state);});

test('worker planner binds the selected namespace before reading and never modifies the durable intent',async()=>{const portal=fixture(),created=ticket(portal);let reads=0;const planner=createNotificationPlanner({productId:policy.productId,portal:{snapshot:async()=>{reads++;return portal.snapshot();}}});await assert.rejects(()=>planner(created.id,{...policy,productId:'foreign-product'}),/NOTIFICATION_PRODUCT_MISMATCH/);assert.equal(reads,0);const before=portal.snapshot();assert.deepEqual((await planner(created.id,policy)).clientActorIds,['owner']);assert.deepEqual(portal.snapshot(),before);});
