import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createApplication} from '../app.mjs';
import {LocalAuth} from '../auth.mjs';
import {DurablePortal} from '../durable.mjs';
let auth,portal,server,dir,invitation;
const origin='http://127.0.0.1:4702',password='A long private browser test password';
test.beforeAll(async()=>{
  dir=mkdtempSync(join(tmpdir(),'wvd-browser-'));auth=new LocalAuth(join(dir,'auth.sqlite'));
  portal=new DurablePortal(join(dir,'portal.sqlite'),{identities:[{id:'owner',active:true},{id:'other',active:true},{id:'admin',active:true,wvdAdmin:true}],projects:[{id:'Client project',businessId:'one',stage:'Design review',nextStep:'Review the first milestone'},{id:'Other private project',businessId:'two'}],memberships:[{actorId:'owner',businessId:'one',active:true,role:'Owner',projectIds:['Client project']},{actorId:'other',businessId:'two',active:true,role:'Owner',projectIds:['Other private project']}],milestones:[{id:'First milestone',projectId:'Client project',currentVersionId:'version-1',status:'awaiting-client'}]});
  invitation=auth.invite('owner','owner@example.test');server=createApplication({portal,auth,allowedOrigin:origin});await new Promise(resolve=>server.listen(4702,'127.0.0.1',resolve));
});
test.afterAll(async()=>{server?.closeIdleConnections();if(server)await new Promise(resolve=>server.close(resolve));auth?.close();portal?.close();if(dir)rmSync(dir,{recursive:true,force:true});});
test('invitation, sign-in, ticket reply, feedback, approval and logout',async({page})=>{
  await page.goto(`/#invite=${invitation.invitationToken}`);
  await expect(page).toHaveURL(origin+'/');
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await page.getByLabel('New password').fill(password);await page.getByRole('button',{name:'Set password',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Password set');
  await page.locator('#login').getByLabel('Email').fill('owner@example.test');await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login').getByRole('button').click();
  await expect(page.getByText('Stage: Design review')).toBeVisible();await expect(page.locator('#projects').getByRole('option')).toHaveCount(1);
  expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
  await expect(page.locator('#workspace')).not.toContainText('Other private project');await expect(page.locator('#admin-overview')).toBeHidden();
  await page.getByLabel('Subject').fill('<img src=x onerror=alert(1)>');await page.getByLabel('Details').fill('Could you explain the next step?');await page.getByRole('button',{name:'Send ticket',exact:true}).click();
  await expect(page.getByRole('status')).toContainText('Ticket saved');await expect(page.getByRole('heading',{name:'<img src=x onerror=alert(1)>'})).toBeVisible();await expect(page.locator('#tickets img')).toHaveCount(0);
  await page.getByRole('button',{name:'Read conversation'}).click();await page.getByLabel('Your reply').fill('Thank you.');await page.getByRole('button',{name:'Send reply',exact:true}).click();await expect(page.getByRole('status')).toContainText('Reply saved');
  await page.getByLabel('Subject').fill('Unsent same-project draft');await page.getByLabel('Details').fill('Unsent same-project details');await page.getByLabel('Feedback',{exact:true}).fill('Ready for the next stage.');await page.getByRole('button',{name:'Send feedback',exact:true}).click();await expect(page.getByRole('status')).toContainText('Feedback saved');await expect(page.getByLabel('Subject')).toHaveValue('Unsent same-project draft');await expect(page.getByLabel('Details')).toHaveValue('Unsent same-project details');
  await page.getByRole('button',{name:'Approve this version'}).click();await expect(page.getByRole('status')).toContainText('Milestone approved');await expect(page.getByText('First milestone — approved')).toBeVisible();
  expect(await page.evaluate(()=>Object.keys(localStorage))).toEqual([]);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByLabel('Subject').fill('Private unsent owner draft');await page.getByLabel('Details').fill('Private unsent owner details');
  await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(page.getByLabel('Subject')).toHaveValue('');await expect(page.getByLabel('Details')).toHaveValue('');await expect(page.locator('#workspace')).toBeHidden();await expect(page.getByRole('status')).toContainText('Signed out');
});

test('Admin can inspect both client projects while client approval stays protected',async({page})=>{
 const invitation=auth.invite('admin','admin@example.test');await auth.redeem(invitation.invitationToken,password,'synthetic-browser-setup');
 await page.goto('/');await page.locator('#login').getByLabel('Email').fill('admin@example.test');await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login button').click();
 const admin=page.locator('#admin-overview');await expect(admin).toBeVisible();await expect(admin).toContainText('Client: one');await expect(admin).toContainText('Client: two');
 await expect(page.getByLabel('Subject')).toHaveValue('');await expect(page.getByLabel('Details')).toHaveValue('');
 portal.createTicket({actorId:'admin',projectId:'Other private project',type:'question',subject:'Synthetic admin question',body:'Synthetic refresh test.',operationId:'admin-refresh'});
 await admin.getByRole('button',{name:'Refresh overview'}).click();await expect(admin.getByRole('article').filter({hasText:'Other private project'})).toContainText('1 support ticket');
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
 await page.getByLabel('Subject').fill('Unsent first-project draft');await page.getByLabel('Details').fill('Unsent first-project details');await admin.getByRole('article').filter({hasText:'Other private project'}).getByRole('button',{name:'Open project'}).click();await expect(page.getByLabel('Subject')).toHaveValue('');await expect(page.getByLabel('Details')).toHaveValue('');await expect(page.locator('#projects')).toHaveValue('Other private project');
 await page.getByLabel('Project stage',{exact:true}).fill('Build');await page.getByLabel('Next project step',{exact:true}).fill('Review the synthetic preview');await page.getByRole('button',{name:'Save progress',exact:true}).click();await expect(page.getByRole('status')).toContainText('Project progress saved');await expect(page.locator('#overview')).toContainText('Stage: Build');
 await page.getByText('Progress history',{exact:true}).click();await expect(page.locator('#overview')).toContainText('Review the synthetic preview');
 await admin.getByRole('article').filter({hasText:'Client project'}).getByRole('button',{name:'Open project'}).click();await expect(page.locator('#projects')).toHaveValue('Client project');
 await page.locator('.publish-review summary').click();await page.getByLabel('New review version',{exact:true}).fill('version-2');await page.getByLabel('Review title',{exact:true}).fill('Synthetic second review');await page.getByLabel('Review text',{exact:true}).fill('Check the revised heading.');await page.getByRole('button',{name:'Publish review',exact:true}).click();await expect(page.getByRole('status')).toContainText('Review version published');await expect(page.locator('#overview')).toContainText('Synthetic second review');
 await expect(page.getByRole('button',{name:'Approve this version',exact:true})).toBeDisabled();
 await page.locator('.create-milestone summary').click();await page.getByLabel('Milestone name',{exact:true}).fill('Second milestone');await page.getByLabel('First review version',{exact:true}).fill('initial');await page.getByLabel('First review title',{exact:true}).fill('Synthetic milestone review');await page.getByLabel('First review text',{exact:true}).fill('Check the second milestone.');await page.getByRole('button',{name:'Add milestone',exact:true}).click();await expect(page.getByRole('status')).toContainText('Milestone added');await expect(page.locator('#overview')).toContainText('Synthetic milestone review');expect((await new AxeBuilder({page}).analyze()).violations).toEqual([]);
 await admin.locator('.create-project summary').click();await admin.getByLabel('Client',{exact:true}).selectOption('one');await admin.getByLabel('New project name',{exact:true}).fill('New isolated project');await admin.getByLabel('Starting stage',{exact:true}).fill('Discovery');await admin.getByLabel('First next step',{exact:true}).fill('Assign client access');await admin.getByRole('button',{name:'Create project',exact:true}).click();await expect(page.getByRole('status')).toContainText('Project created');await expect(page.locator('#projects')).toHaveValue('New isolated project');await expect(page.locator('#overview')).toContainText('Stage: Discovery');expect(portal.projectsFor('owner').map(x=>x.id)).toEqual(['Client project']);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await expect(admin).toBeHidden();await expect(admin).toBeEmpty();
 await page.locator('#login').getByLabel('Email').fill('owner@example.test');await page.locator('#login').getByLabel('Password',{exact:true}).fill(password);await page.locator('#login button').click();await expect(page.locator('#projects').getByRole('option')).toHaveCount(1);await expect(page.locator('#workspace')).not.toContainText('New isolated project');await expect(admin).toBeHidden();
 const review=page.locator('#overview article').filter({has:page.getByRole('heading',{name:'Synthetic second review',exact:true})});await expect(review).toBeVisible();await review.getByRole('button',{name:'Approve this version',exact:true}).click();await expect(page.getByRole('status')).toContainText('Milestone approved');expect(portal.snapshot().receipts.filter(x=>x.versionId==='version-2').length).toBe(1);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
});
